import assert from "node:assert/strict";
import test from "node:test";
import path from "node:path";
import { access, mkdtemp, rm } from "node:fs/promises";
import { chromium } from "playwright";
import { expect } from "@playwright/test";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";
import { createAgentWebServer } from "../src/server.mjs";
import { MemoryRecords } from "../src/database.mjs";
import { ModelCatalog } from "../src/models.mjs";
import { testConfig, waitFor } from "./helpers.mjs";
import { startBrowserSite } from "./fixtures/browser-site.mjs";

let installed = true; try { await access(chromium.executablePath()); } catch { installed = false; }

test("real Chrome extension keeps logins private until the per-chat toggle, and off closes only its automation tab", { skip: !installed, timeout: 60000 }, async t => {
  const root = await mkdtemp("/tmp/relay-personal-test-"), site = await startBrowserSite(); let profile;
  const config = testConfig(path.join(root, "relay"), { AGENT_IDLE_TIMEOUT_MS: "60000" }), records = new MemoryRecords();
  const models = new ModelCatalog(config); models.codex = models.claude = async () => ({ models: [], source: "fixture" });
  const options = { config, records, models, github: { status: async () => ({ connected: false }) }, commands: { list: async () => ({ commands: [] }) } };
  let app = await createAgentWebServer(options); const { url, port } = await app.start();
  await (await app.resources.forOwner(null)).companies.save({ id: "fixture-company", name: "Fixture company" });
  t.after(async () => { await profile?.close(); await app.stop(); await site.close(); await rm(root, { recursive: true, force: true }); });
  const request = async (route, cookie, method = "GET", value) => {
    const response = await fetch(url + route, { method, headers: { "content-type": "application/json", ...(cookie ? { cookie } : {}) }, ...(value ? { body: JSON.stringify(value) } : {}) });
    const body = await response.json(); if (!response.ok) throw Error(`${response.status} ${body.error}`);
    return { body, cookie: response.headers.get("set-cookie")?.split(";")[0] };
  };
  const extension = path.resolve("chrome-extension");
  const launch = () => chromium.launchPersistentContext(path.join(root, "personal-profile"), { channel: "chromium", headless: true, chromiumSandbox: true, viewport: { width: 1600, height: 1000 },
    args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`] });
  profile = await launch();
  const relay = await profile.newPage(), uiErrors = [], consentRequests = [];
  relay.on("pageerror", error => uiErrors.push(error.message));
  const consentRoute = value => /\/privacy$/.test(new URL(value).pathname) ? "privacy" : /\/browser\/access$/.test(new URL(value).pathname) ? "browser-access" : null;
  relay.on("requestfailed", request => {
    const route = consentRoute(request.url()); if (!route) return;
    const error = request.failure()?.errorText || "";
    consentRequests.push({ route, error: /^net::[A-Z_]+$/.test(error) ? error : "network-failure" });
  });
  relay.on("response", response => { const route = consentRoute(response.url()); if (route) consentRequests.push({ route, status: response.status() }); });
  // Fixed endpoint classifications/status only: never bodies, cookies, URLs or
  // pairing codes, including when this fixture fails before consent completes.
  t.after(() => t.diagnostic(JSON.stringify({ consentRequests })));
  await relay.goto(url);
  await expect(relay.locator("#new-chat-button")).toBeEnabled({ timeout: 15000 });
  await relay.getByRole("button", { name: "Browser connections", exact: true }).click();
  await relay.getByLabel("Username", { exact: true }).fill("alice"); await relay.getByLabel("Account password", { exact: true }).fill("private fixture chrome");
  await relay.getByRole("button", { name: "Create private account", exact: true }).click();
  await expect(relay.locator("#browser-account-name")).toContainText("alice");
  const identity = (await profile.cookies(url)).find(c => c.name === "relay_browser_identity");
  const cookie = `${identity.name}=${identity.value}`;
  const account = { cookie, body: (await request("/api/browser-account", cookie)).body };
  await relay.locator("#browser-connection-name").fill("Alice Chrome");
  await relay.locator("#browser-pair-form button[type=submit]").click();
  await expect(relay.locator("#browser-pair-result")).toBeVisible();
  const paired = { code: await relay.locator("#browser-pair-code").inputValue(), id: (await request("/api/browser-connections", cookie)).body.connections[0].id };
  // This pre-existing shared chat is claimed privately only after explicit consent.
  const chat = (await request("/api/chats", null, "POST", { agent: "mock", title: "Private browser fixture" })).body.chat;
  await app.store.update(chat.id, { repositories: [{ fullName: "fixture/project", companyId: "fixture-company" }] });
  const worker = profile.serviceWorkers()[0] || await profile.waitForEvent("serviceworker"), extensionId = new URL(worker.url()).host;
  const personalTab = await profile.newPage(), fixtureUrl = site.url.replace("127.0.0.1", "localhost");
  await personalTab.goto(fixtureUrl); await personalTab.getByRole("button", { name: "Fixture sign in" }).click();
  assert.equal(await personalTab.locator("#session").textContent(), "Signed in as Alice");
  const popup = await profile.newPage(), extensionErrors = [];
  popup.on("pageerror", error => extensionErrors.push(error.message));
  popup.on("console", message => { if (message.type() === "error") extensionErrors.push(message.text()); });
  await popup.goto(`chrome-extension://${extensionId}/popup.html`);
  await popup.locator("#relay-url").fill(url); await popup.locator("#pair-code").fill(paired.code);
  await popup.getByRole("button", { name: "Pair this Chrome profile" }).click();
  await popup.locator("#connection-name").filter({ hasText: "Alice Chrome" }).waitFor({ timeout: 12000 }).catch(async () => {
    const diagnostics = await popup.evaluate(() => ({ valid: document.querySelector("form").checkValidity(), handler: typeof document.querySelector("form").onsubmit, disabled: document.querySelector("form button").disabled }));
    throw Error("Pairing UI: " + await popup.locator("body").innerText() + JSON.stringify({ diagnostics, extensionErrors }));
  });
  await waitFor(async () => (await app.manager.browsers.personal.list(account.body.user))[0]?.online);
  await relay.getByLabel("Close browser connections", { exact: true }).click();
  await relay.goto(`${url}/#chat=${chat.id}`);
  await relay.reload();
  await expect(relay.locator("#signed-chrome-toggle")).not.toBeChecked();
  assert.equal((await request(`/api/chats/${chat.id}/browser/access`, account.cookie)).body.enabled, false);
  await app.manager.browsers.command(chat.id, "navigate", { url: fixtureUrl });
  await waitFor(async () => (await app.manager.browsers.command(chat.id, "evaluate", { expression: "document.querySelector('#session')?.textContent" })) === "Signed out");
  const enableFromUI = async page => {
    await page.locator(".signed-chrome-toggle").click();
    await expect(page.locator("#browser-share-dialog")).toBeVisible();
    assert.equal((await request(`/api/chats/${chat.id}/browser/access`, cookie)).body.enabled, false, "opening the confirmation is not consent");
    await page.locator("#browser-share-confirm").check(); await page.getByRole("button", { name: "Enable for this chat", exact: true }).click();
    await expect(page.locator("#browser-share-dialog")).not.toBeVisible();
    await expect(page.locator("#signed-chrome-toggle")).toBeChecked();
  };
  await enableFromUI(relay);
  assert.equal(app.store.get(chat.id).ownerId, account.body.user.id);
  await relay.getByLabel("Open shared Chrome", { exact: true }).click();
  await expect(relay.locator("#browser-profile-label")).toHaveText("Your signed-in Chrome");
  await app.manager.browsers.command(chat.id, "navigate", { url: fixtureUrl });
  await waitFor(async () => (await app.manager.browsers.command(chat.id, "evaluate", { expression: "document.querySelector('#session')?.textContent" })) === "Signed in as Alice");
  assert.equal(app.manager.browsers.info(chat.id).mode, "personal");
  await expect(relay.locator("#browser-canvas")).toBeVisible();
  await expect(relay.locator("#browser-canvas")).toHaveAttribute("width", "2560");
  await relay.locator("#browser-viewport").selectOption("390x844");
  await expect(relay.locator("#browser-canvas")).toHaveAttribute("width", "780");
  await expect(relay.locator("#browser-canvas")).toHaveAttribute("height", "1688");
  await relay.locator("#browser-viewport").selectOption("1280x800");
  await expect(relay.locator("#browser-canvas")).toHaveAttribute("width", "2560");
  await expect(relay.locator("#browser-tabs")).toBeDisabled();
  const tokenConfig = app.manager.browsers.runtime(chat.id, url).relay_browser, client = new Client({ name: "personal-browser-test", version: "1" });
  await client.connect(new StreamableHTTPClientTransport(new URL(tokenConfig.url), { requestInit: { headers: tokenConfig.headers } }));
  try {
    const result = await client.callTool({ name: "browser_evaluate", arguments: { expression: "document.querySelector('#session').textContent" } });
    assert.equal(JSON.parse(result.content[0].text), "Signed in as Alice", "the real MCP agent transport shares the authorized page");
    const screenshot = await client.callTool({ name: "browser_screenshot", arguments: {} }); assert.equal(screenshot.content[0].type, "image");
  } finally { await client.close(); }
  await assert.rejects(app.manager.browsers.command(chat.id, "navigate", { url }), /hostname cannot be opened/);
  await app.manager.browsers.command(chat.id, "fill", { selector: "#entry", text: "Agent used my authorized profile" });
  await waitFor(async () => (await (await fetch(`${site.url}/observed`)).json()).text === "Agent used my authorized profile");
  await app.manager.browsers.command(chat.id, "evaluate", { expression: "document.querySelector('#entry').select()" });
  assert.deepEqual(await app.manager.browsers.personal.command(chat.id, "copy", { expression: "document.body.textContent='must not run'" }), { text: "Agent used my authorized profile" });
  await relay.screenshot({ path: "/tmp/agent-relay-personal-chrome-desktop.png", fullPage: true });
  const pending = app.manager.browsers.command(chat.id, "evaluate", { expression: "new Promise(resolve => setTimeout(() => resolve('private late result'), 5000))" });
  const rejected = assert.rejects(pending, /revoked|changed|closed/i);
  await relay.locator(".signed-chrome-toggle").click();
  await waitFor(() => !app.manager.browsers.personal.grants.has(chat.id)); await rejected;
  assert.equal(app.manager.browsers.info(chat.id).mode, "guest");
  assert.equal(personalTab.isClosed(), false); assert.equal(await personalTab.locator("#session").textContent(), "Signed in as Alice");
  await expect(relay.locator("#browser-profile-label")).toHaveText("Separate profile");
  await app.manager.browsers.command(chat.id, "navigate", { url: fixtureUrl });
  await waitFor(async () => (await app.manager.browsers.command(chat.id, "evaluate", { expression: "document.querySelector('#session')?.textContent" })) === "Signed out");
  await enableFromUI(relay);
  await expect(popup.locator("#access-status")).toContainText("Agent access ON");
  await popup.getByRole("button", { name: "Stop agent access", exact: true }).click();
  await waitFor(() => !app.manager.browsers.personal.grants.has(chat.id));
  await expect(relay.locator("#signed-chrome-toggle")).not.toBeChecked();
  assert.deepEqual(uiErrors, []); assert.deepEqual(extensionErrors, []);
  // Saved pairing and website cookies survive both Chrome and Relay restarting;
  // active permission never survives either restart.
  await enableFromUI(relay);
  await profile.close(); profile = null;
  await waitFor(() => !app.manager.browsers.personal.grants.has(chat.id));
  await app.stop(); app = await createAgentWebServer({ ...options, config: { ...config, port } }); await app.start();
  profile = await launch();
  await waitFor(async () => (await app.manager.browsers.personal.list(account.body.user))[0]?.online, { timeoutMs: 10000 });
  assert.equal((await request(`/api/chats/${chat.id}/browser/access`, cookie)).body.enabled, false);
  const restored = await profile.newPage(); await restored.goto(fixtureUrl);
  await expect(restored.locator("#session")).toHaveText("Signed in as Alice");
  await request(`/api/chats/${chat.id}/browser/access`, cookie, "PATCH", { enabled: true, confirm: true, connectionId: paired.id });
  await app.manager.browsers.command(chat.id, "navigate", { url: fixtureUrl });
  await waitFor(async () => (await app.manager.browsers.command(chat.id, "evaluate", { expression: "document.querySelector('#session')?.textContent" })) === "Signed in as Alice");
  const automationId = Number(app.manager.browsers.info(chat.id).tabId);
  const restoredWorker = profile.serviceWorkers()[0];
  await restoredWorker.evaluate(id => chrome.tabs.remove(id), automationId);
  await waitFor(() => !app.manager.browsers.personal.grants.has(chat.id));
  assert.equal(restored.isClosed(), false);
  await request(`/api/chats/${chat.id}/browser/access`, cookie, "PATCH", { enabled: true, confirm: true, connectionId: paired.id });
  await app.stop(); app = await createAgentWebServer({ ...options, config: { ...config, port } }); await app.start();
  await waitFor(async () => (await app.manager.browsers.personal.list(account.body.user))[0]?.online, { timeoutMs: 12000 });
  assert.equal((await request(`/api/chats/${chat.id}/browser/access`, cookie)).body.enabled, false, "automatic reconnect to a restarted controller must not restore permission");
  await expect(restored.locator("#session")).toHaveText("Signed in as Alice");
  assert.equal(app.store.get(chat.id).messages.length, 0);
});
