import { test, expect } from "@playwright/test";

test("pin, drag to a custom group, restore grouping, sort, and persist across tabs", async ({ page, context }) => {
  const errors = []; page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  await page.getByRole("button", { name: "Pin Existing alpha", exact: true }).click();
  await expect(page.locator('[data-section="pinned"]')).toContainText("Existing alpha");
  await page.getByRole("button", { name: "Create custom group" }).click();
  await page.getByLabel("Group name", { exact: true }).fill("Sprint planning");
  await page.getByRole("button", { name: "Save group", exact: true }).click();
  const row = page.locator(".chat-row").filter({ hasText: "Existing beta" });
  const target = page.locator('[data-drop-target="Sprint planning"]');
  await row.dragTo(target.locator("summary"));
  await expect(target).toContainText("Existing beta");
  await page.getByLabel("Sort chats").selectOption("created_asc");
  const other = await context.newPage(); await other.goto("/");
  await expect(other.getByLabel("Sort chats")).toHaveValue("created_asc");
  await expect(other.locator('[data-drop-target="Sprint planning"]')).toContainText("Existing beta");
  await other.getByRole("button", { name: "Organize Existing beta", exact: true }).click();
  await other.getByLabel("Move to group", { exact: true }).selectOption("");
  await other.getByLabel("Chat state", { exact: true }).selectOption("pr_open");
  await other.getByRole("button", { name: "Save changes", exact: true }).click();
  await expect(page.locator('[data-section="company:personal"]')).toContainText("Existing beta");
  await expect(page.locator(".chat-row").filter({ hasText: "Existing beta" })).toContainText("PR open");
  await page.reload(); await expect(page.locator('[data-section="pinned"]')).toContainText("Existing alpha");
  expect(errors).toEqual([]);
});

test("GitHub picker preserves repository order, branches, selection and inline errors", async ({ page }) => {
  await page.goto("/"); await page.getByRole("button", { name: /New chat/ }).click();
  await expect(page.locator("#new-chat-title")).toHaveCount(0);
  await page.locator("#connect-github-button").click();
  await page.getByRole("button", { name: "Use this server’s gh login" }).click();
  await expect(page.locator("#github-dialog")).not.toBeVisible();
  await page.locator(".repository-picker-dropdown > summary").click();
  await page.getByLabel("Acme/api", { exact: false }).check();
  await page.getByLabel("Other/library", { exact: false }).check();
  await page.getByLabel("Branch for Acme/api").focus();
  await expect(page.getByLabel("Branch for Acme/api").locator("option")).toHaveCount(2);
  await page.getByLabel("Branch for Acme/api").selectOption("develop");
  await page.getByLabel("Make Other/library primary").click();
  await page.getByLabel("New chat model", { exact: true }).selectOption("fixture-gpt");
  await page.getByLabel("New chat effort", { exact: true }).selectOption("high");
  await expect(page.locator("#repository-group-hint")).toContainText("Other → library");
  await page.getByRole("button", { name: "Create chat", exact: true }).click();
  await expect(page.locator("#new-chat-dialog")).not.toBeVisible();
  await expect(page.locator('[data-section="company:other"]')).toContainText("library");
  await expect(page.getByLabel("Chat model", { exact: true })).toHaveValue("fixture-gpt");
  await expect(page.getByLabel("Chat effort", { exact: true })).toHaveValue("high");
  await page.getByLabel("Chat effort", { exact: true }).selectOption("low");
  await page.reload(); await page.getByRole("button", { name: /New chat/ }).click();
  await expect(page.locator(".repository-chip").first()).toContainText("Other/library");
  await expect(page.getByLabel("Branch for Acme/api")).toHaveValue("develop");
  await expect(page.getByLabel("New chat effort", { exact: true })).toHaveValue("high");
  await expect(page.getByLabel("Chat effort", { exact: true })).toHaveValue("low");
  await page.route("**/api/chats", route => route.request().method() === "POST" ? route.fulfill({ status: 403, json: { error: "GitHub permission revoked. Reconnect your account." } }) : route.continue());
  await page.getByRole("button", { name: "Create chat", exact: true }).click();
  await expect(page.locator("#create-chat-error")).toBeVisible();
  await expect(page.locator("#create-chat-error")).toContainText("permission revoked");
  await expect(page.getByRole("button", { name: "Create chat", exact: true })).toBeEnabled();
});

test("mobile group menu and masked environment editor", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto("/");
  await page.getByRole("button", { name: "Open chats", exact: true }).click();
  await page.getByRole("button", { name: "Organize Existing alpha", exact: true }).click();
  await page.getByLabel("Chat state", { exact: true }).selectOption("archived");
  await page.getByRole("button", { name: "Save changes", exact: true }).click();
  await page.getByRole("button", { name: "Environments", exact: true }).click();
  await page.getByRole("button", { name: "Add environment", exact: false }).click();
  await page.getByLabel("Environment name", { exact: true }).fill("Browser sandbox");
  await page.getByRole("button", { name: "Add variable", exact: false }).click();
  await page.getByLabel("Variable 1 name", { exact: true }).fill("SERVICE_TOKEN");
  await page.getByLabel("Variable 1 value", { exact: true }).fill("private-test-only");
  await page.getByRole("button", { name: "Save environment", exact: true }).click();
  await expect(page.locator("#environment-save-status")).toHaveText("Saved securely");
  await expect(page.getByLabel("Variable 1 value", { exact: true })).toHaveValue("");
  await page.getByRole("button", { name: "Show", exact: true }).click();
  await expect(page.getByLabel("Variable 1 value", { exact: true })).toHaveValue("private-test-only");
  await page.getByRole("button", { name: "Hide", exact: true }).click();
  await expect(page.getByLabel("Variable 1 value", { exact: true })).toHaveAttribute("type", "password");
  await page.screenshot({ path: "test-results/mobile-environments.png", fullPage: true });
});
