import { test, expect } from "@playwright/test";
const created = [];
test.afterEach(async ({ request }) => { for (const id of created.splice(0)) await request.delete(`/api/chats/${id}`); });

test("shared Chrome renders in the third column and accepts mouse and keyboard input with live updates", async ({ page, request }) => {
  await page.setViewportSize({ width: 1600, height: 1000 });
  const errors = []; page.on("pageerror", error => errors.push(error.message));
  const { chat } = await (await request.post("/api/chats", { data: { agent: "mock", title: "Browser visual test" } })).json(); created.push(chat.id);
  await page.goto(`/#chat=${chat.id}`);
  await page.getByLabel("Open shared Chrome", { exact: true }).click();
  await expect(page.locator("#browser-status")).toContainText("Live ·", { timeout: 20000 });
  await page.getByLabel("Browser address", { exact: true }).fill("http://localhost:8883");
  await page.locator("#browser-address-form").getByRole("button", { name: "Go", exact: true }).click();
  await expect(page.getByLabel("Browser tabs", { exact: true })).toContainText("Live development fixture");
  const canvas = page.locator("#browser-canvas"); await expect(canvas).toBeVisible();
  const box = await canvas.boundingBox();
  const geometry = await page.evaluate(() => Object.fromEntries(["sidebar", "conversation", "browser-panel"].map(id => { const b = document.getElementById(id).getBoundingClientRect(); return [id, { left: b.left, right: b.right }]; })));
  expect(geometry.sidebar.right).toBeLessThanOrEqual(geometry.conversation.left);
  expect(geometry.conversation.right).toBeLessThanOrEqual(geometry["browser-panel"].left + 1);
  const color = () => canvas.evaluate(node => [...node.getContext("2d").getImageData(10, 10, 1, 1).data]);
  await expect.poll(async () => (await color())[2]).toBeGreaterThan(240);
  await canvas.click({ position: { x: box.width * 60 / 1280, y: box.height * 120 / 800 } });
  await expect.poll(async () => (await (await request.get("http://127.0.0.1:8883/observed")).json()).clicks).toBe(1);
  await canvas.click({ position: { x: box.width * 60 / 1280, y: box.height * 180 / 800 } });
  await page.keyboard.type("Typed from my Chrome");
  await expect.poll(async () => (await (await request.get("http://127.0.0.1:8883/observed")).json()).text).toBe("Typed from my Chrome");
  await page.keyboard.press("Escape"); await expect(page.getByLabel("Browser address", { exact: true })).toBeFocused();
  await page.locator("#browser-viewport").selectOption("390x844");
  await expect(canvas).toHaveAttribute("width", "390"); await expect(canvas).toHaveAttribute("height", "844");
  await page.locator("#browser-viewport").selectOption("1280x800"); await expect(canvas).toHaveAttribute("width", "1280");
  await request.post("http://127.0.0.1:8883/refresh");
  await expect.poll(async () => (await (await request.get("http://127.0.0.1:8883/observed")).json()).live).toBe("Updated live");
  await page.screenshot({ path: "test-results/shared-browser-desktop.png", fullPage: true });
  await page.getByLabel("Expand browser", { exact: true }).click(); await expect(page.locator("#browser-panel")).toHaveClass(/expanded/);
  await page.getByLabel("Close browser panel", { exact: true }).click();
  await expect(page.locator("#browser-panel")).not.toBeVisible();
  expect((await (await request.get(`/api/chats/${chat.id}`)).json()).chat.messages).toEqual([]);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByLabel("Open shared Chrome", { exact: true }).click(); await expect(page.locator("#browser-status")).toContainText("Live ·");
  expect(await page.locator("#browser-panel").evaluate(node => node.getBoundingClientRect().right)).toBeLessThanOrEqual(390);
  await page.screenshot({ path: "test-results/shared-browser-mobile.png", fullPage: true });
  await page.getByRole("button", { name: "Stop Chrome", exact: true }).click(); await expect(page.locator("#browser-status")).toContainText("Chrome stopped");
  expect(errors).toEqual([]);
});
