import { newId, nowIso } from "./utils.mjs";

// Explicitly requested development fixtures, never generated agent/tool activity.
export function renderingSample(agent, turns = 120) {
  const topics = ["Responsive layout", "Message history", "Markdown tables", "HTML documents", "Code review", "Queue behavior", "Accessibility", "Browser verification", "API errors", "Release checklist", "Session usage", "Workspace navigation"];
  const createdAt = nowIso(), meta = { renderingSample: true };
  const message = (role, text) => ({ id: newId("msg"), role, kind: "message", text, createdAt, meta, ...(role === "assistant" ? { agent } : {}) });
  const messages = [message("system", "Rendering sample begins here. The preceding conversation is unchanged. The following sample requests and responses are display fixtures, not real user requests or agent actions; no commands, tools, or model calls were run to produce them.")];
  for (let i = 1; i <= turns; i++) {
    const topic = topics[(i - 1) % topics.length];
    messages.push(message("user", `Rendering sample ${i} / ${turns}: ${topic}\n\nShow a detailed review with paragraphs, a checklist, a table, and code. Include enough information to test wrapping, message navigation, scrolling, and the document panel. This is sample content only.`));
    const rich = i % 4 === 0 ? `\n\n\`\`\`html\n<article><h1>${topic}</h1><p>Sample document ${i}. Styles are isolated from the surrounding chat.</p><table><thead><tr><th>Viewport</th><th>Layout</th><th>Expected</th></tr></thead><tbody><tr><td>390 px</td><td>Overlay</td><td>Readable controls</td></tr><tr><td>834 px</td><td>Tablet rail</td><td>Separate navigation</td></tr><tr><td>1440 px</td><td>Three columns</td><td>Chat plus preview</td></tr></tbody></table></article>\n\`\`\`` : `\n\n\`\`\`javascript\n// Rendering example only; this code has not been executed.\nexport function sample${i}(items) {\n  return items.filter(item => item.visible).map(item => ({\n    id: item.id,\n    label: item.label ?? "Untitled",\n    selected: item.id === "sample-${i}",\n  }));\n}\n\`\`\``;
    messages.push(message("assistant", `## ${topic} — sample ${i}\n\nThis deliberately long response exercises the transcript layout. **The important result should be easy to find**, while supporting details remain readable at desktop, tablet, and phone widths. The user bubble should sit to the right and the response should use the available reading column without overlapping the composer.\n\n### Observations\n\n1. Keep the original conversation and its stable message anchors intact. Moving between old and new messages should not change which chat is selected.\n2. Preserve ordinary text selection and multiline input behavior. Keyboard navigation should choose slash commands only while the command menu is open.\n3. A long document should scroll within its own panel. Unclosed HTML tags, styles, and wide tables must not affect the sidebar or composer.\n\n| Surface | Narrow screen | Desktop | Expected result |\n|:--|:--|:--|:--|\n| Navigation | Collapsible | Docked sidebar | Current chat stays selected |\n| Conversation | Single column | Center reading column | Long paragraphs wrap |\n| Preview | Overlay | Third column | Independent scrolling |\n| Queue | Compact actions | Send now and remove | Other entries retained |\n\n> Sample note: these are rendering expectations, not claims that an agent has run tests or changed files.\n\n### Checklist\n\n- [x] Include varied Markdown in the sample.\n- [x] Keep inline code such as \`message.id\` distinct from prose.\n- [ ] Verify this layout interactively in your browser.\n- [ ] Try the message rail and jump back to this section.\n\n${rich}\n\n### Further detail\n\nThis paragraph adds realistic reading length after the structured content. Wide code is intentionally contained in its own scrolling region; prose should not cause a horizontal scrollbar across the page. Opening and closing a side panel should retain the transcript position, and returning to the end of a long conversation should leave the composer available.\n\nFor the next check, scroll several screens up, use the message navigator to return to sample ${i}, and compare the highlighted request with this response. Nothing in this fixture authorizes code execution, account access, deployment, or changes to an external service.`));
  }
  return messages;
}
